// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvpkikackxitxysmswit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cGtpa2Fja3hpdHh5c21zd2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjc1NjUsImV4cCI6MjA2NjY0MzU2NX0.FRaj1CkUTNRyfcDA4QLAahM9-BUWtEb8VtHBOXi5FfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);